seed = 1234
output = "output"
exp_name = "debug"

[dataset]
downscale = 2.0
random_bg = true
bgcolor = [1.0, 1.0, 1.0]
use_refined_pose = true
load_depth = false
dataset_dir = "D:\\SMIL\\datasets\\custom_dataset\\dataset"

[smpl]
path = "D:\\SMIL\\datasets\\smpl_models\\"
type = "smpl"
canonical_type = "da-pose"
gender = "male"
subdivide = 1

[model]
learnable_scale = false
use_vertex_gaussians = true
min_edge_len_factor = 0.35
smpl_type = 'smpl'

[trainer]
devices = [0]
max_epochs = 20
deterministic = true
log_every_n_steps = 10

[train]
lr = 1e-3

v_lr = 0.001
shs_lr = 0.02
shape_encoder_lr = 0.0001
opacity_lr = 0.000

scale_lr = 0.01
rotation_lr = 0.001

lambda_ssim = 0.1
gs_loss_weight = 1.0
mesh_loss_weight = 0.1
normal_loss_weight = 1.0
reg_loss_weight = 0.0
mesh_laplacian_loss_weight = 0.01
edge_equal_loss_weight = 0.01


[gaussian]
max_sh_degree = 0