

[dataset]
name = 'xhuman'
root = '/data/lipeng/Shujiazhi/dataset/xhuman'
subject = '00019'

[[dataset.train_list]]
takes = [6, 8]
x_split = 'test'
split = { start = 0, end = -1, skip = 4 }

[[dataset.test_list]]
x_split = 'train'
takes = [4, 5, 7, 9, 10, 11, 12]
split = { start = 0, end = -1, skip = 4 }
